/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'W7500_Flash_Algo' 
 * Target:  'W7500_128' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM0.h"



#endif /* RTE_COMPONENTS_H */
